def CONTAINER_NAME="jenkins-pipeline"
def CONTAINER_TAG="latest"
def DOCKER_HUB_USER="alexuc"
def PORT="3000"

node {

    stage('Initialize'){
        def dockerHome = tool 'docker'
        def mavenHome  = tool 'maven3'
        env.PATH = "${dockerHome}/bin:${mavenHome}/bin:${env.PATH}"
    }

    stage('Checkout') {
        checkout scm
    }

    stage('Build'){
        sh "mvn clean install"
    }

    stage('Create Image'){
        buildDockerImg(CONTAINER_NAME, CONTAINER_TAG)
    }

    stage('Deploy App'){
        deployAppToDocker(CONTAINER_NAME, CONTAINER_TAG, DOCKER_HUB_USER, PORT)
    }

}

def buildDockerImg(containerName, tag){
    sh "docker build -t $containerName:$tag  -t $containerName --pull --no-cache ."
    echo "Docker image build completed"
}

def deployAppToDocker(containerName, tag, dockerHubUser, httpPort){
    sh "docker pull $dockerHubUser/$containerName"
    sh "docker run -d --rm -p $httpPort:$httpPort --name $containerName $dockerHubUser/$containerName:$tag"
    echo "Application deployed on http port: ${httpPort}"
}